/**
 * Algorithm Fusion Tests — DoneWell Audio
 *
 * These tests validate the fusion engine (fuseAlgorithmResults) against
 * synthetic scenarios generated by Gemini Ultra's vulnerability analysis.
 * Each scenario constructs an algorithm score vector that represents a
 * specific real-world audio situation and asserts the expected verdict.
 *
 * Test categories:
 *   1. Weight summation validation
 *   2. Effective weights when comb is absent
 *   3. Single-algorithm isolation (no single algo reaches FEEDBACK)
 *   4. Gemini's 8 vulnerability scenarios (current weights)
 *   5. Three-model consensus vulnerability scenarios (TEST-004)
 *   6. Pure feedback / pure music / pure noise baselines
 *   7. Edge cases (single algorithm, warmup, null scores)
 *
 * References:
 *   - algorithmFusion.ts: fuseAlgorithmResults(), FUSION_WEIGHTS
 *   - Gemini Ultra vulnerability analysis (March 2026)
 *   - Deep Algorithm Audit findings DA-004 (confidence warmup penalty)
 */

import { describe, it, expect } from 'vitest'
import {
  fuseAlgorithmResults,
  FUSION_WEIGHTS,
  DEFAULT_FUSION_CONFIG,
  type FusionConfig,
} from '@/lib/dsp/fusionEngine'
import { buildScores, type ScoreInput } from '../helpers/mockAlgorithmScores'

// ── Helper ───────────────────────────────────────────────────────────────────

/** Run fusion with a simplified score input and return the result */
function fuse(
  input: ScoreInput,
  contentType: 'speech' | 'music' | 'compressed' | 'unknown' = 'unknown',
  config?: Partial<FusionConfig>,
  peakFrequencyHz?: number
) {
  return fuseAlgorithmResults(
    buildScores(input),
    contentType,
    { ...DEFAULT_FUSION_CONFIG, ...config },
    peakFrequencyHz
  )
}

// ═════════════════════════════════════════════════════════════════════════════
// 1. WEIGHT VALIDATION
// ═════════════════════════════════════════════════════════════════════════════

describe('Fusion Weight Profiles', () => {
  it('DEFAULT weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.DEFAULT
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr
    expect(sum).toBeCloseTo(1.0, 10)
  })

  it('SPEECH weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.SPEECH
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr
    expect(sum).toBeCloseTo(1.0, 10)
  })

  it('MUSIC weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.MUSIC
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr
    expect(sum).toBeCloseTo(1.0, 10)
  })

  it('COMPRESSED weights sum to 1.0', () => {
    const w = FUSION_WEIGHTS.COMPRESSED
    const sum = w.msd + w.phase + w.spectral + w.comb + w.ihr + w.ptmr
    expect(sum).toBeCloseTo(1.0, 10)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 2. EFFECTIVE WEIGHTS WITHOUT COMB
//
// When comb pattern is absent (the common case), comb weight drops out of
// totalWeight. Each algorithm's effective share = nominal / totalNoComb.
// ═════════════════════════════════════════════════════════════════════════════

describe('Effective Weights — Comb Absent', () => {
  /**
   * For each profile, totalNoComb = 1 - combWeight.
   * Effective share = algorithmWeight / totalNoComb.
   */

  it('SPEECH MSD effective weight is ~34.7% when comb is absent', () => {
    const w = FUSION_WEIGHTS.SPEECH
    const totalNoComb = 1 - w.comb
    const effectiveMsd = w.msd / totalNoComb
    // MSD 0.33 / (1 - 0.05) = 0.3474
    expect(effectiveMsd).toBeCloseTo(0.347, 2)
  })

  it('MUSIC Phase effective weight is ~39.1% when comb is absent', () => {
    const w = FUSION_WEIGHTS.MUSIC
    const totalNoComb = 1 - w.comb
    const effectivePhase = w.phase / totalNoComb
    // Phase 0.36 / (1 - 0.08) = 0.3913
    expect(effectivePhase).toBeCloseTo(0.391, 2)
  })

  it('COMPRESSED Phase effective weight is ~32.6% when comb is absent', () => {
    const w = FUSION_WEIGHTS.COMPRESSED
    const totalNoComb = 1 - w.comb
    const effectivePhase = w.phase / totalNoComb
    // Phase 0.30 / (1 - 0.08) = 0.3261
    expect(effectivePhase).toBeCloseTo(0.326, 2)
  })

})

// ═════════════════════════════════════════════════════════════════════════════
// 3. SINGLE-ALGORITHM ISOLATION — No algorithm alone should reach FEEDBACK
//
// With all other algorithms at score=0 and existingScore=0, a single
// algorithm at max cannot accumulate enough weight to cross the threshold.
// ═════════════════════════════════════════════════════════════════════════════

describe('Single-Algorithm Isolation', () => {
  it('MSD=1.0 alone cannot reach FEEDBACK (probability < 0.35)', () => {
    const result = fuse(
      { msd: 1.0, phase: 0, spectral: 0, comb: 0, ihr: 0, ptmr: 0 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeLessThan(0.35)
  })

  it('MSD+Phase both=1.0 still below FEEDBACK threshold (< 0.60)', () => {
    const result = fuse(
      { msd: 1.0, phase: 1.0, spectral: 0, comb: 0, ihr: 0, ptmr: 0 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeLessThan(0.60)
  })

  it('MSD+Phase+Spectral all=1.0 exceeds 0.60 (with PTMR support)', () => {
    // ADV-001: ptmr=0 now triggers PTMR breadth gate (×0.80), so provide
    // minimal PTMR support to avoid penalty
    const result = fuse(
      { msd: 1.0, phase: 1.0, spectral: 1.0, comb: 0, ihr: 0, ptmr: 0.3 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 4. GEMINI HISTORICAL VULNERABILITY SCENARIOS
//
// These scenarios used to expose the old fusion failures. They now serve as
// regression coverage for the fixed behavior.
// ═════════════════════════════════════════════════════════════════════════════

describe('Gemini Vulnerability Scenarios — DEFAULT Profile', () => {
  /**
   * Scenario: Sustained synthesizer note
   * Flat envelope (MSD=0.8), highly tonal (Phase=0.9), rich harmonics (IHR=0.1),
   * moderate flatness (Spectral=0.4), prominent (PTMR=0.7, Existing=0.8).
   * No comb pattern.
   *
   * Historical failure: music was incorrectly classified as feedback.
   * Gemini calculated the old behavior at 0.650 (above 0.60 threshold).
   */
  it('FIXED: sustained synth note now stays UNCERTAIN', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.9, spectral: 0.4, comb: 0, ihr: 0.1, ptmr: 0.7 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeLessThan(0.42)
    expect(result.verdict).toBe('UNCERTAIN')
  })

  /**
   * Scenario: Low-frequency feedback in reverberant room
   * Slow MSD growth (MSD=0.4), smeared phase (Phase=0.5), pure tone
   * (Spectral=0.9, IHR=0.9, PTMR=0.8), prominent (Existing=0.9). No comb.
   *
   * Historical failure: real feedback was missed.
   * Gemini calculated the old behavior at 0.571 (below 0.60 threshold).
   */
  it('FIXED: low-freq reverberant feedback now reaches FEEDBACK', () => {
    const result = fuse(
      { msd: 0.4, phase: 0.5, spectral: 0.9, comb: 0, ihr: 0.9, ptmr: 0.8 },
      'unknown'
    )
    expect(result.verdict).toBe('FEEDBACK')
    expect(result.feedbackProbability).toBeLessThan(0.65)
  })
})

describe('Gemini Vulnerability Scenarios — SPEECH Profile', () => {
  /**
   * Scenario: Speaker holding a long vowel "Ummmm" into compressed mic
   * Stable amplitude (MSD=0.9), highly tonal (Phase=0.8), complex harmonics
   * (IHR=0.2, Spectral=0.5), prominent (PTMR=0.6, Existing=0.7).
   *
   * Historical failure: speech was incorrectly classified as feedback.
   * Gemini calculated the old behavior at 0.710 (well above threshold).
   * ROOT CAUSE: MSD weight of 0.40 makes any stable amplitude trigger detection.
   */
  it('FIXED: sustained vowel now stays UNCERTAIN', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.8, spectral: 0.5, comb: 0, ihr: 0.2, ptmr: 0.6 },
      'speech'
    )
    expect(result.feedbackProbability).toBeLessThan(0.42)
    expect(result.verdict).toBe('UNCERTAIN')
  })

  /**
   * Scenario: Fast ringing feedback clamped by system limiter
   * Zero growth (MSD=0.1), perfect tone (Phase=0.9, Spectral=0.9, IHR=0.9,
   * PTMR=0.9), prominent (Existing=0.8).
   *
   * Historical failure: real feedback was missed because limiter killed MSD.
   * Gemini calculated the old behavior at 0.525 (below threshold).
   * ROOT CAUSE: MSD weight of 0.40 means zero-growth feedback can't compensate.
   */
  it('FIXED: limiter-clamped feedback now reaches FEEDBACK', () => {
    const result = fuse(
      { msd: 0.1, phase: 0.9, spectral: 0.9, comb: 0, ihr: 0.9, ptmr: 0.9 },
      'speech'
    )
    expect(result.verdict).toBe('FEEDBACK')
    expect(result.feedbackProbability).toBeLessThan(0.65)
  })
})

describe('Gemini Vulnerability Scenarios — MUSIC Profile', () => {
  /**
   * Scenario: Intentional musical guitar feedback
   * Flat envelope (MSD=0.8), perfectly coherent (Phase=0.95), some harmonics
   * (IHR=0.2, Spectral=0.6), very prominent (PTMR=0.8, Existing=0.9).
   *
   * Intentional guitar feedback is acoustically close to unwanted feedback, so
   * this remains acceptable as a possible corrective path.
   * Gemini calculated the old behavior at 0.711.
   */
  it('Intentional guitar feedback remains acceptable as POSSIBLE or FEEDBACK', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.95, spectral: 0.6, comb: 0, ihr: 0.2, ptmr: 0.8 },
      'music'
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    expect(['POSSIBLE_FEEDBACK', 'FEEDBACK']).toContain(result.verdict)
  })

  /**
   * Scenario: Unwanted feedback hidden in dense loud mix
   * Phase ruined by mix masking (Phase=0.3), slowly growing (MSD=0.6),
   * pure tone in FFT gap (Spectral=0.8, IHR=0.8, PTMR=0.7), Existing=0.6.
   *
   * Historical failure: real feedback was missed in dense mix.
   * Gemini calculated the old behavior at 0.496 (well below threshold).
   * ROOT CAUSE: Phase weight of 0.35 means dense mixes that mask phase cause failure.
   */
  it('FIXED: feedback hidden in dense mix now reaches FEEDBACK', () => {
    const result = fuse(
      { msd: 0.6, phase: 0.3, spectral: 0.8, comb: 0, ihr: 0.8, ptmr: 0.7 },
      'music'
    )
    expect(result.feedbackProbability).toBeLessThan(0.60)
    expect(result.verdict).toBe('FEEDBACK')
  })
})

describe('Gemini Vulnerability Scenarios — COMPRESSED Profile', () => {
  /**
   * Scenario: Compressed backing track with clean flute sample
   * Slight growth (MSD=0.5), perfectly tonal (Phase=0.95), moderate purity
   * (Spectral=0.6, IHR=0.3, PTMR=0.6), prominent (Existing=0.8).
   *
   * Historical failure: clean flute was classified as feedback.
   * Gemini calculated the old behavior at 0.663.
   */
  it('FIXED: compressed flute sample now stays UNCERTAIN', () => {
    const result = fuse(
      { msd: 0.5, phase: 0.95, spectral: 0.6, comb: 0, ihr: 0.3, ptmr: 0.6, compressed: true },
      'unknown' // contentType doesn't matter when compressed=true
    )
    expect(result.feedbackProbability).toBeLessThan(0.35)
    expect(result.verdict).toBe('UNCERTAIN')
  })

  /**
   * Scenario: Feedback fighting against heavy mix bus compressor
   * Compressor pumping randomizes phase (Phase=0.2), growing amplitude
   * (MSD=0.8), pure tone underneath (Spectral=0.8, IHR=0.9, PTMR=0.8),
   * Existing=0.7.
   *
   * Historical failure: real feedback was missed because compressor destroyed
   * the very signal (phase) that COMPRESSED mode relied on most.
   * Gemini calculated the old behavior at 0.508. ROOT CAUSE: Phase weight of 0.38 was a
   * single point of failure.
   *
   * POST-FIX-005: IMPROVED — redistributing phase weight to spectral/ihr/ptmr
   * means the strong non-phase signals (spectral=0.8, ihr=0.9, ptmr=0.8)
   * now carry enough weight to cross the threshold. Real feedback detected!
   */
  it('compressor-pumped feedback now reaches FEEDBACK', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.2, spectral: 0.8, comb: 0, ihr: 0.9, ptmr: 0.8, compressed: true },
      'unknown'
    )
    expect(result.feedbackProbability).toBeGreaterThan(0.60)
    expect(result.verdict).toBe('FEEDBACK')
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 5. THREE-MODEL CONSENSUS HISTORICAL VULNERABILITY SCENARIOS (TEST-004)
//
// These scenarios used to pin cross-validation failures. Keep them aligned
// with the corrected runtime behavior.
// ═════════════════════════════════════════════════════════════════════════════

describe('Consensus Vulnerability: DEFAULT Profile', () => {
  it('V1 — FIXED: Synth note (MSD+Phase dominant) stays UNCERTAIN', () => {
    const result = fuse(
      { msd: 0.85, phase: 0.80, spectral: 0.55, ihr: 0.20, ptmr: 0.35, comb: 0 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeLessThan(0.40)
    expect(result.verdict).toBe('UNCERTAIN')
  })

  it('V2 — spectral/IHR/PTMR corroboration remains on the possible feedback path when MSD+phase are blind', () => {
    const result = fuse(
      { msd: 0, phase: 0, spectral: 0.80, ihr: 0.80, ptmr: 0.80, comb: 0 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeLessThan(0.35)
    expect(result.verdict).toBe('POSSIBLE_FEEDBACK')
  })
})

describe('Consensus Vulnerability: SPEECH Profile', () => {
  it('V3 — MSD-only conviction no longer reaches FEEDBACK', () => {
    const result = fuse(
      { msd: 1.0, phase: 0, spectral: 0.60, ihr: 0.40, ptmr: 0.60, comb: 0 },
      'speech'
    )
    // FIX-004: SPEECH MSD reduced from 0.40→0.33.
    // Before: prob=0.634 (FEEDBACK). After: prob≈0.579 (POSSIBLE_FEEDBACK).
    // MSD-only conviction no longer crosses the 0.60 threshold.
    expect(result.feedbackProbability).toBeLessThan(0.60)
    expect(result.verdict).not.toBe('FEEDBACK')
  })

  it('V4 — no-MSD feedback stays on the possible feedback path through spectral/IHR/PTMR support', () => {
    const result = fuse(
      { msd: 0, phase: 0.20, spectral: 0.80, ihr: 0.80, ptmr: 0.80, comb: 0 },
      'speech'
    )
    expect(result.feedbackProbability).toBeGreaterThanOrEqual(0.35)
    expect(result.verdict).toBe('POSSIBLE_FEEDBACK')
  })
})

describe('Consensus Vulnerability: MUSIC Profile', () => {
  it('V5 — FIXED: Phase-dominant music no longer convicts on phase alone', () => {
    const result = fuse(
      { msd: 0, phase: 1.0, spectral: 0.80, ihr: 0.60, ptmr: 0.40, comb: 0 },
      'music'
    )
    expect(result.feedbackProbability).toBeLessThan(0.45)
    expect(result.verdict).toBe('UNCERTAIN')
  })

  it('V6 — no-phase music feedback stays on the possible feedback path through MSD/spectral/IHR support', () => {
    const result = fuse(
      { msd: 0.80, phase: 0, spectral: 0.80, ihr: 0.80, ptmr: 0.20, comb: 0 },
      'music'
    )
    expect(result.feedbackProbability).toBeLessThan(0.40)
    expect(result.verdict).toBe('POSSIBLE_FEEDBACK')
  })
})

describe('Consensus Vulnerability: COMB Pattern', () => {
  it('V7 — Comb flip: same scores, comb presence crosses threshold', () => {
    const scores = { msd: 0.60, phase: 0.60, spectral: 0.60, ihr: 0.60, ptmr: 0.60, comb: 0 }

    const noComb = fuse(scores, 'unknown')
    // With uniform scores of 0.60, weighted average ≈ 0.60.
    // Comb absent means no comb contribution or doubling.
    // Floating point: 0.6000000000000001, so use closeTo.
    expect(noComb.feedbackProbability).toBeCloseTo(0.60, 10)

    const withComb = fuse({ ...scores, comb: 0.80 }, 'unknown')
    expect(withComb.feedbackProbability).toBeGreaterThan(0.60)

  })
})

describe('Consensus Vulnerability: COMPRESSED Profile', () => {
  it('V8 — phase conviction under compression no longer reaches FEEDBACK', () => {
    const result = fuse(
      { msd: 0, phase: 1.0, spectral: 0.40, ihr: 0.40, ptmr: 0.60, compressed: true, comb: 0 },
      'unknown'
    )
    // FIX-005: COMPRESSED phase reduced 0.38→0.30, prob drops below 0.60
    expect(result.feedbackProbability).toBeLessThan(0.60)
    expect(result.verdict).not.toBe('FEEDBACK')
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 6. BASELINE SCENARIOS — Known Ground Truth
// ═════════════════════════════════════════════════════════════════════════════

describe('Baseline: Obvious Cases', () => {
  it('Pure feedback: all algorithms agree → FEEDBACK', () => {
    const result = fuse(
      { msd: 0.95, phase: 0.95, spectral: 0.95, comb: 0, ihr: 0.95, ptmr: 0.95 },
      'unknown'
    )
    expect(result.verdict).toBe('FEEDBACK')
    expect(result.feedbackProbability).toBeGreaterThan(0.90)
    expect(result.confidence).toBeGreaterThan(0.80)
  })

  it('Pure music: all algorithms agree → low probability', () => {
    const result = fuse(
      { msd: 0.05, phase: 0.1, spectral: 0.05, comb: 0, ihr: 0.05, ptmr: 0.05 },
      'music'
    )
    // Verdict may be NOT_FEEDBACK or UNCERTAIN depending on confidence;
    // the key assertion is that probability stays well below threshold.
    expect(result.feedbackProbability).toBeLessThan(0.15)
    expect(result.verdict).not.toBe('FEEDBACK')
  })

  it('Silence: no algorithm data → zero probability', () => {
    const result = fuse(
      {}, // All null
      'unknown'
    )
    // No algorithms contribute (existing weight removed), result should be 0.0
    expect(result.feedbackProbability).toBe(0.0)
  })

  it('Feedback with comb pattern: comb doubles weight and boosts score', () => {
    const result = fuse(
      { msd: 0.8, phase: 0.85, spectral: 0.7, comb: 0.9, ihr: 0.8, ptmr: 0.8 },
      'unknown'
    )
    expect(result.verdict).toBe('FEEDBACK')
    expect(result.contributingAlgorithms).toContain('Comb')
    // Comb should increase total probability
    const noComb = fuse(
      { msd: 0.8, phase: 0.85, spectral: 0.7, comb: 0, ihr: 0.8, ptmr: 0.8 },
      'unknown'
    )
    expect(result.feedbackProbability).toBeGreaterThan(noComb.feedbackProbability)
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 7. EDGE CASES
// ═════════════════════════════════════════════════════════════════════════════

describe('Edge Cases', () => {
  /**
   * DA-004: Confidence warmup penalty
   * When only MSD has data and other algorithms are null, the confidence
   * calculation should not penalize a strong single-algorithm detection.
   */
  it('DA-004: single strong MSD should still reach POSSIBLE_FEEDBACK', () => {
    const result = fuse(
      { msd: 0.9, msdFrames: 15 },
      'speech'
    )
    // With only MSD (0.9) contributing (existing weight removed), we want at least POSSIBLE_FEEDBACK
    // Current behavior: confidence may be low due to single-algorithm detection
    // At minimum, probability should reflect the strong MSD signal
    expect(result.feedbackProbability).toBeGreaterThan(0.5)
  })

  it('Content type selects correct weight profile', () => {
    const scores = { msd: 0.5, phase: 0.5, spectral: 0.5, comb: 0, ihr: 0.5, ptmr: 0.5 }

    const speech = fuse(scores, 'speech')
    const music = fuse(scores, 'music')

    // SPEECH weights MSD at 0.33, MUSIC at 0.08
    // With same feedbackScores, SPEECH should produce higher probability
    // because MSD (0.5) * 0.40 > MSD (0.5) * 0.15 only matters when
    // combined with other weights. All scores equal means probability ≈ 0.5 for both.
    // But the weight distribution differences still create slight variations.
    expect(speech.feedbackProbability).toBeCloseTo(0.5, 1)
    expect(music.feedbackProbability).toBeCloseTo(0.5, 1)
  })

  it('Compressed audio triggers COMPRESSED weight profile', () => {
    const result = fuse(
      { msd: 0.5, phase: 0.5, spectral: 0.5, comb: 0, ihr: 0.5, ptmr: 0.5, compressed: true },
      'speech' // Content type is overridden by compressed detection
    )
    expect(result.reasons.some(r => r.includes('Compression detected'))).toBe(true)
  })

  it('custom mode can run an MSD-oriented subset', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.9, spectral: 0.9, comb: 0.9, ihr: 0.9, ptmr: 0.9 },
      'unknown',
      { mode: 'custom', enabledAlgorithms: ['msd', 'ihr', 'ptmr'] }
    )
    expect(result.contributingAlgorithms).toContain('MSD')
    expect(result.contributingAlgorithms).not.toContain('Phase')
    expect(result.contributingAlgorithms).not.toContain('Spectral')
    expect(result.contributingAlgorithms).not.toContain('Comb')
  })

  it('custom mode can run a phase-oriented subset', () => {
    const result = fuse(
      { msd: 0.9, phase: 0.9, spectral: 0.9, comb: 0.9, ihr: 0.9, ptmr: 0.9 },
      'unknown',
      { mode: 'custom', enabledAlgorithms: ['phase', 'ihr', 'ptmr'] }
    )
    expect(result.contributingAlgorithms).not.toContain('MSD')
    expect(result.contributingAlgorithms).toContain('Phase')
  })

  it('feedbackProbability is always in [0, 1]', () => {
    // Extreme high scores
    const high = fuse(
      { msd: 1.0, phase: 1.0, spectral: 1.0, comb: 1.0, ihr: 1.0, ptmr: 1.0 },
      'unknown'
    )
    expect(high.feedbackProbability).toBeLessThanOrEqual(1.0)
    expect(high.feedbackProbability).toBeGreaterThanOrEqual(0.0)

    // Extreme low scores
    const low = fuse(
      { msd: 0.0, phase: 0.0, spectral: 0.0, comb: 0, ihr: 0.0, ptmr: 0.0 },
      'unknown'
    )
    expect(low.feedbackProbability).toBeLessThanOrEqual(1.0)
    expect(low.feedbackProbability).toBeGreaterThanOrEqual(0.0)
  })

  it('Verdict thresholds are correct', () => {
    // FEEDBACK requires probability >= 0.60 AND confidence >= 0.6
    // POSSIBLE_FEEDBACK requires probability >= 0.42 AND confidence >= 0.4
    // NOT_FEEDBACK requires probability < 0.3 AND confidence >= 0.6

    const feedback = fuse(
      { msd: 0.95, phase: 0.95, spectral: 0.95, comb: 0, ihr: 0.95, ptmr: 0.95 },
      'unknown'
    )
    expect(feedback.verdict).toBe('FEEDBACK')

    const notFeedback = fuse(
      { msd: 0.02, phase: 0.05, spectral: 0.02, comb: 0, ihr: 0.02, ptmr: 0.02 },
      'unknown'
    )
    // Low scores yield low probability; verdict is NOT_FEEDBACK or UNCERTAIN
    // depending on confidence (variance between small values reduces agreement).
    expect(notFeedback.feedbackProbability).toBeLessThan(0.10)
    expect(notFeedback.verdict).not.toBe('FEEDBACK')
  })
})

// ═════════════════════════════════════════════════════════════════════════════
// 8. LOW-FREQUENCY PHASE SUPPRESSION (ADV-002)
// ═════════════════════════════════════════════════════════════════════════════

describe('Low-Frequency Phase Suppression (ADV-002)', () => {
  const highPhaseScores = { msd: 0.5, phase: 1.0, spectral: 0.5, comb: 0, ihr: 0.5, ptmr: 0.5 }

  it('phase is suppressed at 100 Hz (below 200 Hz threshold)', () => {
    const normal = fuse(highPhaseScores, 'unknown', undefined, undefined)
    const lowFreq = fuse(highPhaseScores, 'unknown', undefined, 100)

    // Low-frequency version should have lower probability due to phase × 0.5
    expect(lowFreq.feedbackProbability).toBeLessThan(normal.feedbackProbability)
  })

  it('phase is NOT suppressed at 500 Hz (above 200 Hz threshold)', () => {
    const normal = fuse(highPhaseScores, 'unknown', undefined, undefined)
    const midFreq = fuse(highPhaseScores, 'unknown', undefined, 500)

    // Above 200 Hz: no suppression, same probability
    expect(midFreq.feedbackProbability).toBeCloseTo(normal.feedbackProbability, 10)
  })

  it('phase is NOT suppressed when peakFrequencyHz is undefined', () => {
    const withoutFreq = fuse(highPhaseScores, 'unknown', undefined, undefined)
    const withHighFreq = fuse(highPhaseScores, 'unknown', undefined, 1000)

    // Both should be identical: no suppression
    expect(withoutFreq.feedbackProbability).toBeCloseTo(withHighFreq.feedbackProbability, 10)
  })

  it('suppression at 50 Hz reduces phase influence significantly', () => {
    // Use MUSIC profile where phase is dominant (35% weight)
    const normal = fuse(highPhaseScores, 'music', undefined, undefined)
    const subBass = fuse(highPhaseScores, 'music', undefined, 50)

    const delta = normal.feedbackProbability - subBass.feedbackProbability
    // Phase score halved × 35% nominal weight → expect noticeable drop
    expect(delta).toBeGreaterThan(0.05)
  })
})
