/**
 * Mode Baselines — frozen detector policy for each mode.
 *
 * Extracted from OPERATION_MODES in constants.ts. These are the authoritative
 * starting point for threshold derivation. Live overrides are applied on top
 * of these values.
 *
 * @see types/settings.ts for ModeBaseline interface
 * @see lib/settings/deriveSettings.ts for how baselines compose with local environment + overrides
 */

import type { ModeBaseline, ModeId } from '@/types/settings'

/**
 * Frozen mode baselines. Values extracted from OPERATION_MODES in constants.ts.
 * These are `as const` to prevent accidental mutation.
 */
export const MODE_BASELINES: Readonly<Record<ModeId, ModeBaseline>> = {
  speech: {
    modeId: 'speech',
    label: 'Speech',
    description: 'Corporate & Conference',
    feedbackThresholdDb: 20,
    ringThresholdDb: 5,
    growthRateThreshold: 1.0,
    fftSize: 8192,
    minFrequency: 150,
    maxFrequency: 10000,
    sustainMs: 180,
    clearMs: 400,
    confidenceThreshold: 0.35,
    prominenceDb: 8,
    eqPreset: 'surgical',
    aWeightingEnabled: true,
    defaultInputGainDb: 0,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 1000,
  },
  worship: {
    modeId: 'worship',
    label: 'Worship',
    description: 'House of Worship',
    feedbackThresholdDb: 35,
    ringThresholdDb: 5,
    growthRateThreshold: 2.0,
    fftSize: 8192,
    minFrequency: 100,
    maxFrequency: 12000,
    sustainMs: 200,
    clearMs: 500,
    confidenceThreshold: 0.45,
    prominenceDb: 12,
    eqPreset: 'surgical',
    aWeightingEnabled: false,
    defaultInputGainDb: 2,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 2000,
  },
  liveMusic: {
    modeId: 'liveMusic',
    label: 'Live Music',
    description: 'Concerts & Events',
    feedbackThresholdDb: 42,
    ringThresholdDb: 8,
    growthRateThreshold: 4.0,
    fftSize: 4096,
    minFrequency: 60,
    maxFrequency: 16000,
    sustainMs: 240,
    clearMs: 600,
    confidenceThreshold: 0.55,
    prominenceDb: 14,
    eqPreset: 'heavy',
    aWeightingEnabled: false,
    defaultInputGainDb: 0,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 5000,
  },
  theater: {
    modeId: 'theater',
    label: 'Theater',
    description: 'Drama & Musicals',
    feedbackThresholdDb: 28,
    ringThresholdDb: 4,
    growthRateThreshold: 1.5,
    fftSize: 8192,
    minFrequency: 150,
    maxFrequency: 10000,
    sustainMs: 180,
    clearMs: 400,
    confidenceThreshold: 0.40,
    prominenceDb: 10,
    eqPreset: 'surgical',
    aWeightingEnabled: true,
    defaultInputGainDb: 4,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 1000,
  },
  monitors: {
    modeId: 'monitors',
    label: 'Monitors',
    description: 'Stage Wedges',
    feedbackThresholdDb: 15,
    ringThresholdDb: 3,
    growthRateThreshold: 0.8,
    fftSize: 4096,
    minFrequency: 200,
    maxFrequency: 6000,
    sustainMs: 140,
    clearMs: 300,
    confidenceThreshold: 0.35,
    prominenceDb: 8,
    eqPreset: 'surgical',
    aWeightingEnabled: false,
    defaultInputGainDb: 0,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 500,
  },
  broadcast: {
    modeId: 'broadcast',
    label: 'Broadcast',
    description: 'Studio & Podcast',
    feedbackThresholdDb: 22,
    ringThresholdDb: 3,
    growthRateThreshold: 1.0,
    fftSize: 8192,
    minFrequency: 80,
    maxFrequency: 12000,
    sustainMs: 180,
    clearMs: 350,
    confidenceThreshold: 0.30,
    prominenceDb: 8,
    eqPreset: 'surgical',
    aWeightingEnabled: true,
    defaultInputGainDb: 0,
    defaultAutoGainTargetDb: -24,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 1000,
  },
  outdoor: {
    modeId: 'outdoor',
    label: 'Outdoor',
    description: 'Open Air & Festivals',
    feedbackThresholdDb: 38,
    ringThresholdDb: 6,
    growthRateThreshold: 2.5,
    fftSize: 4096,
    minFrequency: 100,
    maxFrequency: 12000,
    sustainMs: 200,
    clearMs: 450,
    confidenceThreshold: 0.45,
    prominenceDb: 12,
    eqPreset: 'heavy',
    aWeightingEnabled: true,
    defaultInputGainDb: 0,
    ignoreWhistle: false,
    defaultTrackTimeoutMs: 2000,
  },
} as const
